# Generated by Django 4.2 on 2025-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_description_product_name_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
