# Generated by Django 4.2 on 2025-02-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pictures',
            new_name='images',
        ),
    ]
